AllCops: 
  Include:
    - 'app/**/*.rb'
    - 'lib/**/*.rb'
    - 'lib/**/*.rake'
  Exclude:
    - 'config/**/*.rb'
    - 'vendor/**/*'
    - 'spec/**/*'
    - 'db/**/*.rb'
    - 'bin/**/*'
    - 'public/uploads/*'

Metrics/LineLength:
  Max: 100

Style/Documentation:
  Enabled: false
  
Style/PredicateName:
  Enabled: false

